### ISSUE TITLE
Request: Make background colors different.

### ISSUE THREAD

**Issue by OlsonBolson-dev** [dracula/betterdiscord#11]
On Discord, they are a lot of colors even if they're not very different and Dracula theme makes them the same it is really hard to see a difference, e.x. embed messages from a bot has the same color as the background, so you would like to change it a little be it would be really nice, thanks.

**Comment by AceKiron** [comment]
I agree with this person, I like to put my servers in folders to keep them organized. The Dracula theme doesn't give the folders an unique background color, which just makes it look even more chaotic than without folders at all.

**Comment by wasi-master** [comment]
And codeblocks don't have any seperation from the background
![image](https://user-images.githubusercontent.com/63045920/143382911-8991960e-b006-4566-b201-2fd472b0771c.png)
Now this isn't a huge issue since they have a monospaced font but some seperation would be helpful

**Comment by mrhappyma** [comment]
This is fixed with the new version
