### ISSUE TITLE
Small gray borders

### ISSUE THREAD

**Issue by Thomas-Philippot** [dracula/betterdiscord#18]
Since a couple of days I can see borders again between the channel list and the chat, and other boxes who had no borders before.
Is that intended ?

**Comment by Kab1r** [comment]
Yes, this is intended

**Comment by wasi-master** [comment]
The theme didn't originally have them but after getting complaints about having no seperation between elements due to them being the same color they were added in https://github.com/dracula/betterdiscord/commit/08417bd6818310bf6e4638db03a6b234f7b095e4
