### ISSUE TITLE
Low contrast on selected channel

### ISSUE THREAD

**Issue by jetblackrx89** [dracula/betterdiscord#34]
It seems that after either an update to BetterDiscord v1.9.3 or the theme itself, some elements have extremely poor contrast, like the channel highlight color for the currently-viewed channel in the sidebar, making them very difficult to see. Here is an unthemed vs unthemed view for comparison.

<img width="300" alt="Screenshot 2023-06-23 at 9 59 03 PM" src="https://github.com/dracula/betterdiscord/assets/7515801/aa39a6e5-9985-467f-83c3-623e49c60cf6">
<img width=300" alt="Screenshot 2023-06-23 at 9 58 51 PM" src="https://github.com/dracula/betterdiscord/assets/7515801/54ade3ec-c9bf-4520-b096-ab5108cab639">

**Comment by mrhappyma** [comment]
That's a good point, I have Discord's funky emojis + colored channels experiment thing so didn't see this. Are there any other elements I missed that have bad contrast?

For context, this was a theme update. There were a lot of issues with the theme with unthemed elements and particularly bad looking sections. I thought about it and eventually ended up redoing the theme entirely (about a week ago).

**Comment by mrhappyma** [comment]
I'll get this fixed tomorrow :+1:

**Comment by mrhappyma** [comment]
Sorry I never replied to this! As I remember it,
I couldn't seem to find a selector that would work for this, so it might not be possible to theme separately.

**Comment by mrhappyma** [comment]
The colors are very similar, but it should be themed...

I'll hold on merging for now. I've been really busy lately and haven't had time to look at the theme very much - including breakages in #36. I agree with most of what you've said. I need to find some time and look into this more later.

On your final note: these "container_b2ce9c" style class names have seemed consistent (mostly) and from my knowledge are the only way to theme individual elements.
