### ISSUE TITLE
Usage of normalized classes.

### ISSUE THREAD

**Issue by Tropix126** [dracula/betterdiscord#6]
Hi, i'm a theme developer and part of the BD community. After looking through the source code, it seems that your theme utilizes BetterDiscord's class normalizer function. This is just a quick word of warning. 

Normalized classes were introduced years ago when discord started mass obfuscation of the classnames in large chunks. It was easier to simply fix this by appending `.da-` before classnames, however this is not the case anymore. The normalizer doesn't apply well today, since they often change the root name as well. Normalized classes also cause some conflicts on generic names, such as `.da-container`, which could mean anything of 40 or 50 different elements. The main issue here is that normalized classes will be depreceated soon for the reasons listed above, and any theme utilizing them will break. I suggest switching away from them as soon as possible to avoid future issues.

**Comment by KabirKwatra** [comment]
#### Affected CSS:
https://github.com/dracula/betterdiscord/blob/a4586750ca6f90e533a87d370199033a81f83960/base.css#L34-L44
