### ISSUE TITLE
Request: make the background of code blocks a darker color compared to the normal background color.

### ISSUE THREAD

**Issue by Pistrie** [dracula/betterdiscord#7]
Currently, a code block has the same color as the normal background.

**Comment by Kab1r** [comment]
[Dracula Color Pallet](https://github.com/dracula/dracula-theme#color-palette) only provides so many colors.

**Comment by wasi-master** [comment]
@Kab1r then add some outline or something simillar

**Comment by Kab1r** [comment]
Source Blocks Seem to now have outlines
